// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwjvqtusnhahjlzafixp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3anZxdHVzbmhhaGpsemFmaXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTUzMjcsImV4cCI6MjA1OTg5MTMyN30.LTh4vNu2-Ck0Chg8cSeSF01Dl_Tb4q6DByACQLwTV1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);