
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwjvqtusnhahjlzafixp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3anZxdHVzbmhhaGpsemFmaXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTUzMjcsImV4cCI6MjA1OTg5MTMyN30.LTh4vNu2-Ck0Chg8cSeSF01Dl_Tb4q6DByACQLwTV1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Helper function to check if a user has access to a garage
export const checkGarageAccess = async (garageId: string) => {
  try {
    const { data, error } = await supabase
      .rpc('check_garage_and_installation_requests', { garage_id_param: garageId });
      
    if (error) throw error;
    
    return {
      hasAccess: data?.[0]?.user_has_access || false,
      garageName: data?.[0]?.garage_name,
      requestsCount: data?.[0]?.installation_requests_count,
      error: data?.[0]?.error_message
    };
  } catch (error: any) {
    console.error("Error checking garage access:", error);
    return { hasAccess: false, error: error.message };
  }
};
